server:
    port: 8080
spring:
    datasource:
        driver-class-name: org.h2.Driver
        username: sa
        url: jdbc:h2:mem:dbMango
        password: ''
    sql:
        init:
            mode: always
    jpa:
        defer-datasource-initialization: 'true'
        hibernate:
        ddl-auto: create
